name: estudy_gpt
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  calendar_view: ^1.4.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_database: ^11.3.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_html: ^3.0.0
  flutter_inappwebview: ^6.1.5
  flutter_langdetect: ^0.0.2
  flutter_markdown: ^0.7.7+1
  flutter_pdfview: ^1.4.0+1
  google_generative_ai: 0.4.7
  google_sign_in: ^6.3.0
  home_widget: ^0.7.0+1
  http: ^1.3.0
  intl: ^0.20.2
  markdown_widget: ^2.3.2+8
  permission_handler: ^12.0.0+1
  provider: ^6.1.5
  receive_sharing_intent:
    git:
      url: https://github.com/KasemJaffer/receive_sharing_intent
      ref: 2cea396843cd3ab1b5ec4334be4233864637874e
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  syncfusion_flutter_pdf: ^29.2.4
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900

  assets:
    - assets/images/
